services:
  localstack:
    container_name: localstack_infra
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510:4510" # Reservado para cuando LocalStack Pro levante el RDS
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LS_TOKEN}
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - red-cloud-local

networks:
  red-cloud-local:
    driver: bridge