spring.application.name=ActivosTecnologicos

# Configuración global de seguridad (Aplica para local y producción)
app.jwt.secretKey=panTieso@1988kamurocho||orem ipsum dolor sit amet, consectetur adipiscing elit.Etiam nec viverra ex, in consequat ante.
app.jwt.expiration-minutes=60