name: CI/CD Pipeline Local (Terraform + LocalStack)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Checkout del Código
        uses: actions/checkout@v4

      - name: 2. Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Compilar Proyecto Spring Boot (JAR)
        run: ./mvnw clean package -DskipTests

      - name: 4. Crear Infraestructura con Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: 5. Autenticar Docker con LocalStack ECR
        run: |
          aws --endpoint-url=http://localhost:4566 ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin localhost:4566

      - name: 6. Build, Tag & Push de la Imagen a LocalStack
        run: |
          docker build -t activos-tecnologicos-repo:latest .
          docker tag activos-tecnologicos-repo:latest localhost:4566/activos-tecnologicos-repo:latest
          docker push localhost:4566/activos-tecnologicos-repo:latest