name: CI/CD Pipeline Local (Terraform + LocalStack)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Checkout del Código
        uses: actions/checkout@v4

      - name: 2. Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Compilar Proyecto Spring Boot (JAR)
        run: ./mvnw clean package -DskipTests

      - name: 4. Inicializar Terraform y Crear SOLO el Repositorio ECR
        run: |
          cd terraform
          terraform init
          # El flag -target le dice que solo cree este recurso por ahora
          terraform apply -target="aws_ecr_repository.app_repo" -auto-approve

      - name: 5. Build, Tag & Push de la Imagen (Usando 127.0.0.1)
        run: |
          docker build -t activos-tecnologicos-repo:latest .
          docker tag activos-tecnologicos-repo:latest localhost.localstack.cloud:4510/activos-tecnologicos-repo:latest
          docker push localhost.localstack.cloud:4510/activos-tecnologicos-repo:latest

      - name: 6. Desplegar el resto de la Infraestructura (VPC, RDS, ECS)
        run: |
          cd terraform
          # Esto aplicará todo lo demás que falta en tu main.tf
          terraform apply -auto-approve